<article
	class="p-4
    prose
    lg:prose-xl
    prose-teal
    dark:prose-invert
    prose-headings:text-green-500
    dark:prose-headings:text-green-400
    prose-p:text-gray-900
    dark:prose-p:text-lime-200
    prose-a:text-red-900
    dark:prose-a:text-red-500
    prose-hr:border-emerald-800
    prose-hr:bg-emerald-800
    prose-hr:dark:border-emerald-500
    prose-hr:dark:bg-emerald-500
    "
>
	<slot />
</article>
